@startuml SIS

class Organization {
    name : string
    address : string
    phoneNumber : string
    email : string
    url : string
    contact : Contact_person
    identifier : int

}

class Company {

}
Company <|- Organization

class Research_group{

}
Research_group <|- Organization

class Educational_institute{

}
Educational_institute <|- Organization

class Internship {

}

class Intermediate_internship {

}
Intermediate_internship <|- Internship

class Minor_internship {

}
Minor_internship <|- Internship
Minor_internship o- Minor

class Graduation_internship {

}
Graduation_internship <|- Internship

class Assignment {

}

class Research_assignment {

}
Research_assignment <|- Assignment

class Minor_assignment {

}
Minor_assignment <|- Assignment
Minor_assignment o- Minor

class Engineering_assignment {

}
Engineering_assignment <|- Assignment

class IPerson{
    firstName : string
    lastName : string

}

class Student {

}
Student <|. IPerson

class Contact_person {
    functionTitle : string
    email : string
    phoneNumber : string
    departmentName : string

}
Contact_person <|. IPerson
Contact_person 1 o- 1 Organization

class Minor {

}
@enduml