@startuml SIS

class Organization {
    name : string
    address : string
    phoneNumber : string
    email : string
    url : string
    contact : Contact_person
    identifier : int

}

class Company {

}
Company <|- Organization

class Research_group{

}
Research_group <|- Organization

class Educational_institute{

}
Educational_institute <|- Organization

class Period {
    year : int
    semester : int     '1 or 2
}

class Internship {
    dateOfSubmission : DateTime
    projectTitle : string
    shortDescription : string
    longDescription : string
    finalGrade : float?
    status : InternshipStatus
}

Internship --> Period

class Intermediate_internship

class Minor_internship {
    minor : Minor
}

class Graduation_internship 

Internship <|-- Intermediate_internship
Internship <|-- Minor_internship
Internship <|-- Graduation_internship

class Assignment {
    description : string
}
Assignment o- Student

class Research_assignment
class Minor_assignment {
    minor : Minor
}

class Engineering_assignment

Assignment <|-- Research_assignment
Assignment <|-- Minor_assignment
Assignment <|-- Engineering_assignment

class IPerson{
    firstName : string
    lastName : string

}

class Student {
    studentNumber : uint
    assignment : Assignment

}
Student <|. IPerson

class Contact_person {
    functionTitle : string
    email : string
    phoneNumber : string
    departmentName : string

}
Contact_person <|. IPerson
Contact_person o- Organization

class Minor {
    moduleName : string

}
Minor o- Minor_internship
Minor o- Minor_assignment

class Application {
    applicationId : int
    submittedAt : Date
    status : ApplicationStatus
}

enum ApplicationStatus {
    SUBMITTED
    APPROVED
    REJECTED
}

Student "1" o-- "0..*" Application
Application "0..*" --> "1" Internship

Intership o-- Student
Student --> Assignment

@enduml